//@ sourceMappingURL=heightEqualizer.map
// Generated by CoffeeScript 1.6.1

/*
高さ揃え
------------------------------------
target…グループの親要素
targetChildren…高さを揃えたい要素
columns…高さを揃えたい1グループあたりの要素数（デフォルトはtarget内のtargetChildrenの数）
------------------------------------

【使用例】
#高さ揃え
layout3col02 = $('.col-03-02')
layout3col03 = $('.col-03-03')
layout4col01 = $('.col-04-01')
$(window).load ->
	if layout3col02.length and $('.box-03').length
		heightEqualizer layout3col02, '.box-03'
	if layout3col03.length
		heightEqualizer layout3col03, '.segment'
	if layout4col01.length
		heightEqualizer layout4col01, '.segment'
	return
*/


(function() {
  var heightEqualizer;

  heightEqualizer = function(target, targetChildren, columns) {
    target.each(function() {
      var childs, count, equalizeTarget, last, maxHeight;
      count = 0;
      maxHeight = 0;
      childs = [];
      equalizeTarget = $(this).find(targetChildren);
      last = equalizeTarget.length - 1;
      if (last > 0) {
        if (columns === void 0) {
          columns = equalizeTarget.length;
        }
      }
      return equalizeTarget.each(function(i) {
        count = i % columns;
        childs[count] = $(this);
        if (count === 0 || $(this).height() > maxHeight) {
          maxHeight = $(this).height();
        }
        if (i === last || count === columns - 1) {
          $.each(childs, function(i, t) {
            return t.height(maxHeight);
          });
        }
      });
    });
  };

}).call(this);
