//@ sourceMappingURL=Img_rollover.map
// Generated by CoffeeScript 1.6.1

/*
ロールオーバー
------------------------------------
element…ロールオーバー対象要素
normalState…ロールオーバー前の画像の接尾辞
hoverState…ロールオーバー後の画像の接尾辞
currentClass…ロールオーバーイベントを起こしたくない際に付加するクラス（グロナビのカレント等）

【使用例】
#ロールオーバー設定
 hovertOptions =
    element: $('.roll')
	normalState: '_normal'
	hoverState: '_hover'
    currentClass: 'now'
imgHover = new Img_rollover(hovertOptions)

------------------------------------
*/


(function() {
  var Img_rollover;

  Img_rollover = (function() {

    Img_rollover.prototype.defaults = {
      element: $('a'),
      normalState: '_o',
      hoverState: '_h',
      currentClass: 'current'
    };

    function Img_rollover(options) {
      var _this = this;
      this.options = $.extend({}, this.defaults, options);
      this.element = this.options.element;
      this.img = this.element.find('img');
      this.normalState = this.options.normalState;
      this.hoverState = this.options.hoverState;
      this.img.each(function(index, element) {
        var srcs;
        _this.targetImage = $(element);
        _this.targetParent = _this.targetImage.parent(_this.element);
        if (!_this.targetImage.hasClass(_this.options.currentClass)) {
          srcs = _this._prepareSrcs(_this.targetImage);
          _this._preload(srcs.src_on);
          _this._eventify(_this.targetParent, _this.targetImage, srcs.src_off, srcs.src_on);
        }
      });
    }

    Img_rollover.prototype._prepareSrcs = function(targetImage) {
      var src, src_off;
      src_off = targetImage.attr('src');
      src = {
        src_off: src_off,
        src_on: src_off.replace(this.normalState, this.hoverState)
      };
      return src;
    };

    Img_rollover.prototype._preload = function(src_on) {
      $('<img />').attr('src', src_on);
    };

    Img_rollover.prototype._eventify = function(targetParent, targetImage, src_off, src_on) {
      var _this = this;
      targetParent.on('mouseenter focus', function() {
        return _this._toOver(targetImage, src_on);
      });
      targetParent.on('mouseleave blur', function() {
        return _this._toNormal(targetImage, src_off);
      });
    };

    Img_rollover.prototype._toOver = function(targetImage, src_on) {
      targetImage.attr('src', src_on);
    };

    Img_rollover.prototype._toNormal = function(targetImage, src_off) {
      targetImage.attr('src', src_off);
    };

    return Img_rollover;

  })();

}).call(this);
